# Generated by Django 3.0.5 on 2020-04-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_auto_20200426_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
